name: Code with Shadman
title: Code with Shadman
description: Easy-to-understand tutorials on the .NET stack with C# language
meta_description: "Easy-to-understand tutorials on the .NET stack with C# language."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: "https://codewithshadman.com"
google_analytics: 'UA-114994933-6'
disqus_shortname: kudchikarsk-github-io
plugins: [jekyll-paginate, jekyll-redirect-from, jekyll-sitemap]

# Details for the RSS feed generator
url:            'https://codewithshadman.com'
author:         'Shadman Kudchikar'

permalink: /:title/

twitter: iamshadmank # replace by your username
facebook: shadman.kudchikar # replace by your username
email: kudchikarsk@gmail.com
subscribers: true